version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      APP_NAME: SportKai
      APP_ENV: local
      APP_VERSION: v0.0.1
      APP_HOST: localhost
      APP_PORT: 8080
      APP_SECRET_KEY: H1M1T5U
      DB_DRIVER: mysql
      DB_HOST: localhost
      DB_PORT: 3396
      DB_USER: root
      DB_PASSWORD: Elysian123!
      DB_NAME: sport_kai
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Elysian123!
      MYSQL_DATABASE: sport_kai
    ports:
      - "3398:3306"
